### ISSUE TITLE
autosave with vim keybindings

### ISSUE THREAD

**Issue by rparrish** [rundel/livecode#4]
Running into issues when vim keybindings are active in RStudio and auto_save = TRUE. 

Autosaving while typing new characters in insert mode updates the server content as expected, however, the editor comes back in command mode rather than staying in insert mode.  Only work-around I've found is to turn off auto_save entirely and manually save the file every so often. 

I'm not familiar with the other keybinding modes that RStudio supports (Emacs, Sublime) so not sure if they have similar or other issues.

**Comment by rundel** [comment]
Interesting, I don't use any of these keybinding options and so I hadn't seen this. We're somewhat constrained by what the rstudioapi functions let us get away with. One small positive is that the new preview version (1.3) allows much more programmatic control over preferences and that may allow us to check for this kind of setting before and after saving.

I'll have to investigate further - thanks for reporting this.

**Comment by rundel** [comment]
Ah ok, playing around with it I clearly had not read carefully enough - I am seeing the Insert Mode -> Command Mode on save now.  Super annoying and I'm not entirely sure what we can do about it since this seems to be a IDE issue. I'll open a issue with them and see if we get a response from anyone on the ide team.

The same issue actually occurs if you use RStudio's builtin save and write on idle feature.

**Comment by rundel** [comment]
Looks like this is getting fixed in the IDE in the 1.3 branch - not sure when it will be available but it should go into preview release relatively soon I hope.
